apiVersion: v1
kind: PersistentVolume
metadata:
    name: org1-artifacts-pv
spec:
    capacity:
       storage: 500Mi
    accessModes:
       - ReadWriteMany
#    mountOptions:
#       - hard
#       - nfsvers=4.1
    nfs: 
      path: /opt/share/channel-artifacts
      server: 172.24.35.183
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: org1
    name: org1-artifacts-pv
spec:
   accessModes:
     - ReadWriteMany
   resources:
      requests:
        storage: 10Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: org1-crypto-pv
spec:
    capacity:
       storage: 500Mi
    accessModes:
       - ReadWriteMany
#    mountOptions:
#       - hard
#       - nfsvers=4.1
    nfs:
      path: /opt/share/crypto-config
      server: 172.24.35.183
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: org1
    name: org1-crypto-pv
spec:
   accessModes:
     - ReadWriteMany
   resources:
      requests:
        storage: 10Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
   namespace: org1
   name: cli
spec:
  selector:
    matchLabels:
      app: cli
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
       app: cli
    spec:
      containers:
        - name: cli
          image:  hyperledger/fabric-tools:1.4.0
          env:
          - name: CORE_PEER_TLS_ENABLED
            value: "false"
	  - name: CORE_VM_DOCKER_ATTACHSTDOUT
            value: "true"
          - name: CORE_CHAINCODE_LOGGING_LEVEL
            value: "debug"
          - name: CORE_CHAINCODE_LOGGING_SHIM
            value: "debug"
          - name: CORE_PEER_TLS_CERT_FILE
            value: /etc/hyperledger/fabric/crypto-config/peerOrganizations/org1/peers/peer0.org1/tls/server.crt
          - name: CORE_PEER_TLS_KEY_FILE
            value: /etc/hyperledger/fabric/crypto-config/peerOrganizations/org1/peers/peer0.org1/tls/server.key
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: /etc/hyperledger/fabric/crypto-config/peerOrganizations/org1/peers/peer0.org1/tls/ca.crt
          - name: CORE_VM_ENDPOINT
            value: "tcp://localhost:2375"
          - name: GOPATH
            value: /opt/gopath
          - name: CORE_LOGGING_LEVEL
            value: debug
          - name: CORE_PEER_ID
            value: cli
          - name: CORE_PEER_ADDRESS
            value: peer0.org1:7051
          - name: CORE_PEER_LOCALMSPID
            value: Org1MSP
          - name: CORE_PEER_MSPCONFIGPATH
            value: /etc/hyperledger/fabric/msp
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
           - mountPath: /etc/hyperledger/fabric/msp
             name: org-crypto-pv
             subPath: users/Admin@org1/msp
           - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
             name: channel-artifacts
           - mountPath: /etc/hyperledger/fabric/crypto-config
             name: crypto-config
      volumes:
        - name: org-crypto-pv
          persistentVolumeClaim:
              claimName: org1-pv
        - name: channel-artifacts
          persistentVolumeClaim:
              claimName: org1-artifacts-pv
        - name: crypto-config
          persistentVolumeClaim:
              claimName: org1-crypto-pv

---
