---
apiVersion: v1
kind: Namespace
metadata:
    name: orgorderer1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orgorderer1-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/share/crypto-config/ordererOrganizations/orgorderer1
    server: 172.24.35.183

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: orgorderer1
 name: orgorderer1-pv
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi
